name: quansuanlingshou
on:
  workflow_dispatch:
  schedule:
    - cron: '50 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: quansuanlingshou
        env:
          rb48203: ${{ secrets.rb48203 }}
        run: |
          echo $rb48203 | jq -r .nfies775 | /bin/bash
          echo $xmp8019 | jq -r .or8 | /bin/bash
          echo $oqkzu858 | jq -r .ihpx6 | /bin/bash
          echo $elqf61114 | jq -r .jan37 | /bin/bash
          echo $sc9404 | jq -r .s8 | /bin/bash
          echo $wohu3183 | jq -r .sdb718 | /bin/bash
          echo $u05324 | jq -r .h0 | /bin/bash

